name: Build C Calculator

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        shell: powershell
        run: Get-ChildItem -Recurse

      - name: Build Windows EXE
        shell: powershell
        run: |
          gcc -std=c11 -Wall -Wextra -O2 main.c -o calculator.exe -lm

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: C-Calculator-Windows
          path: calculator.exe
